# Generated by Django 5.2.5 on 2025-09-11 14:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Endereço de email')),
                ('user_name', models.CharField(max_length=150, unique=True, verbose_name='Usuário')),
                ('first_name', models.CharField(max_length=150, verbose_name='Primeiro nome')),
                ('last_name', models.CharField(max_length=150, verbose_name='Sobrenome')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('endereco_rua', models.CharField(blank=True, max_length=255, null=True)),
                ('endereco_numero', models.CharField(blank=True, max_length=10, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(blank=True, max_length=15, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('registro_profissional', models.CharField(blank=True, max_length=50, null=True, verbose_name='CRP ou CRM')),
                ('data_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de registro')),
                ('tipo', models.CharField(choices=[('normal', 'Usuário Normal'), ('psicologo', 'Psicólogo/Psiquiatra'), ('admin', 'Administrador')], default='normal', max_length=20)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
