# Generated by Django 5.2.5 on 2025-09-13 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('newuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
            },
            bases=('user.newuser',),
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='registro_profissional',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='endereco_rua',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='endereco_numero',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='tipo',
        ),
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('newuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Usuário Normal',
                'verbose_name_plural': 'Usuários Normais',
            },
            bases=('user.newuser',),
        ),
        migrations.CreateModel(
            name='PsicologoUser',
            fields=[
                ('newuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('registro_profissional', models.CharField(max_length=50, verbose_name='CRP ou CRM')),
                ('endereco_rua', models.CharField(blank=True, max_length=255, null=True)),
                ('endereco_numero', models.CharField(blank=True, max_length=10, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(blank=True, max_length=15, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Psicólogo',
                'verbose_name_plural': 'Psicólogos',
            },
            bases=('user.newuser',),
        ),
    ]
