# Generated by Django 5.2.5 on 2025-09-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_adminuser_remove_newuser_data_nascimento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='normaluser',
            old_name='data_nascimento',
            new_name='born',
        ),
        migrations.AddField(
            model_name='newuser',
            name='gender',
            field=models.CharField(choices=[('1', 'Masculino'), ('0', 'Feminino')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
