# Generated by Django 5.2.5 on 2025-08-25 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triagem',
            name='tr27',
        ),
        migrations.RemoveField(
            model_name='triagem',
            name='tr28',
        ),
        migrations.RemoveField(
            model_name='triagem',
            name='tr29',
        ),
        migrations.RemoveField(
            model_name='triagem',
            name='tr30',
        ),
        migrations.RemoveField(
            model_name='triagem',
            name='tr31',
        ),
        migrations.RemoveField(
            model_name='triagem',
            name='tr32',
        ),
        migrations.RemoveField(
            model_name='triagem',
            name='tr33',
        ),
        migrations.RemoveField(
            model_name='triagem',
            name='tr34',
        ),
        migrations.RemoveField(
            model_name='triagem',
            name='tr35',
        ),
        migrations.RemoveField(
            model_name='triagem',
            name='tr36',
        ),
        migrations.RemoveField(
            model_name='triagem',
            name='tr37',
        ),
        migrations.RemoveField(
            model_name='triagem',
            name='tr38',
        ),
        migrations.RemoveField(
            model_name='triagem',
            name='tr39',
        ),
        migrations.RemoveField(
            model_name='triagem',
            name='tr40',
        ),
        migrations.RemoveField(
            model_name='triagem',
            name='tr41',
        ),
        migrations.RemoveField(
            model_name='triagem',
            name='tr42',
        ),
        migrations.RemoveField(
            model_name='triagem',
            name='tr43',
        ),
    ]
