# Generated by Django 5.2.5 on 2025-09-14 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagem',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='triagem',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default=20, max_length=1),
            preserve_default=False,
        ),
    ]
