# Generated by Django 5.2.5 on 2025-09-14 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0002_triagem_age_triagem_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagem',
            name='gender',
            field=models.CharField(choices=[('1', 'Masculino'), ('0', 'Feminino')], max_length=1),
        ),
    ]
