# Generated by Django 5.2.5 on 2025-08-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0003_triagem_demo1_triagem_demo10_triagem_demo11_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagem',
            name='sexo',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
