# Generated by Django 5.2.5 on 2025-08-25 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0004_triagem_sexo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='triagem',
            old_name='idade',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='triagem',
            old_name='sexo',
            new_name='gender',
        ),
    ]
